### ISSUE TITLE
isoformat does not take `timespec` to specify the customized output

### ISSUE THREAD

**Issue by meysam81** [slashmili/python-jalali#46]
I am in need of something like this in `jdatetime`:
```
import datetime
datetime.datetime.now().isoformat(timespec='seconds')
# output: '2019-06-04T17:04:46'

**Comment by farzadghanei** [comment]
`timespec` optional argument is a quite recent feauter, [added since Python 3.6](https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat).

Compatibility with the standard library API is highest priority.
> This module exactly follows Python Standard datetime module's methods http://docs.python.org/release/2.7.1/library/datetime.html

I'm not saying this feature doesn't need to be implemented, but the context helps to understand priorities.

Meanwhile I noticed The `isoformat` method is still missing [sep](https://docs.python.org/2/library/datetime.html#datetime.datetime.isoformat) argument, which was available since Python 2.7.
